### ISSUE TITLE
Get keyboard navigation to work as on live demo page

### ISSUE THREAD

**Issue by katrinkerber** [lukehaas/Scrollify#191]
On the [live demo page](https://projects.lukehaas.me/scrollify/) keyboard navigation works pretty good (not perfectly though) for the spacebar, go to top/bottom keys, one up/down keys, and up/down arrows.

However, using version 1.0.8 on my site, only the up/down arrows work, none of the other keys.

How can I get the keyboard keys to fire the scroll events as they do on the demo site?

I did start checking for keypresses myself, but thought maybe there is an easy setting I am missing somewhere...

**Comment by lukehaas** [comment]
Thanks, this is a good point. The spacebar should trigger scrolling. I'll add that in the next version. For now you'll need to capture the space press event yourself and trigger the scrollify.next method.

**Comment by lukehaas** [comment]
This is resolved in 1.0.9

**Comment by katrinkerber** [comment]
Thank you very much Luke.

The space bar is now working, but the go to top/bottom keys and one up/down keys still don't. I've added them myself, which is fine, but thought you might want to include those by default too.

Might also be worth including an option for Shift + Space to trigger going up one section.

**Comment by lukehaas** [comment]
I'm not sure why the up/down keys aren't working for you. That's been a key feature since the first release.
Do you know what what keycode is being generated when you hit your up/down keys?

**Comment by katrinkerber** [comment]
Yeah, they work on your demo site, but not on my install for some reason. Not sure why.

Here’s what I am using to get them working:

```
if (e.keyCode === 36) {
  // back to top
  $.scrollify.move(0);
}
if (e.keyCode === 35) {
  // to bottom
  $.scrollify.move("#footer");
}
if (e.keyCode === 34) {
  // one up
  $.scrollify.next();
}
if (e.keyCode === 33) {
  // one down
  $.scrollify.previous();
}
```

**Comment by lukehaas** [comment]
This is interesting. The standard codes for up/down are 38/40. Do you know if you have some kind of alternative key bindings, or maybe an unusual keyboard?

**Comment by lukehaas** [comment]
Ah, I see. don't worry. Just read that 34/33 are the page up, page down keys.
Yeah, I should add those into Scrollify.
Thanks for your help.

**Comment by katrinkerber** [comment]
Yeah, I meant those special up/down keys, not the arrow up/down ones, which work perfectly :)

Thank you for such a great plugin.

**Comment by lukehaas** [comment]
Added page up and page down key codes
